#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

local_dir="$1"
[[ -d "$local_dir" ]]

init_diag_variables "$local_dir"
mkdir -p "$REMOTE_DIAG_DIR"
rsync -qrt --inplace --exclude=_index.html "$local_dir/" "$REMOTE_DIAG_DIR"
