#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

download_dir=/var/lib/rnode-static/packages
url="$1"

if [[ -z "$url" ]]; then
	echo "Usage: $0 <url>" >&2
	exit 1
fi

# Turn "http://example.com/foo/bar?baz=a/b/c" into "bar_baz_a_b_c"
filename="$(sed 's|[^?#]*/||; s/[^0-9A-Za-z_\.-]/_/g' <<<$url)"
file=$download_dir/$filename

mkdir -p $download_dir
logcmd curl -fsSL -z $file -o $file "$url"
logcmd apt install -y --allow-downgrades $file
