#!/usr/bin/env python

import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

import lib_rnode_tls

if len(sys.argv) != 2:
    print('Usage: {} <pem-key-file>'.format(sys.argv[0]), file=sys.stderr)
    sys.exit(1)

pem_path = Path(sys.argv[1])
pem_bytes = pem_path.read_bytes()
key = serialization.load_pem_private_key(
    pem_bytes, password=None, backend=default_backend())
node_id = lib_rnode_tls.get_node_id_raw(key)

print(node_id.hex())
